// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// FibonacciClient is the client API for Fibonacci service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FibonacciClient interface {
	// Sends a greeting
	GetSequence(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (Fibonacci_GetSequenceClient, error)
}

type fibonacciClient struct {
	cc grpc.ClientConnInterface
}

func NewFibonacciClient(cc grpc.ClientConnInterface) FibonacciClient {
	return &fibonacciClient{cc}
}

func (c *fibonacciClient) GetSequence(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (Fibonacci_GetSequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Fibonacci_serviceDesc.Streams[0], "/proto.Fibonacci/GetSequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &fibonacciGetSequenceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fibonacci_GetSequenceClient interface {
	Recv() (*FibonacciReply, error)
	grpc.ClientStream
}

type fibonacciGetSequenceClient struct {
	grpc.ClientStream
}

func (x *fibonacciGetSequenceClient) Recv() (*FibonacciReply, error) {
	m := new(FibonacciReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FibonacciServer is the server API for Fibonacci service.
// All implementations must embed UnimplementedFibonacciServer
// for forward compatibility
type FibonacciServer interface {
	// Sends a greeting
	GetSequence(*FibonacciRequest, Fibonacci_GetSequenceServer) error
	mustEmbedUnimplementedFibonacciServer()
}

// UnimplementedFibonacciServer must be embedded to have forward compatible implementations.
type UnimplementedFibonacciServer struct {
}

func (UnimplementedFibonacciServer) GetSequence(*FibonacciRequest, Fibonacci_GetSequenceServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSequence not implemented")
}
func (UnimplementedFibonacciServer) mustEmbedUnimplementedFibonacciServer() {}

// UnsafeFibonacciServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FibonacciServer will
// result in compilation errors.
type UnsafeFibonacciServer interface {
	mustEmbedUnimplementedFibonacciServer()
}

func RegisterFibonacciServer(s grpc.ServiceRegistrar, srv FibonacciServer) {
	s.RegisterService(&_Fibonacci_serviceDesc, srv)
}

func _Fibonacci_GetSequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FibonacciRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FibonacciServer).GetSequence(m, &fibonacciGetSequenceServer{stream})
}

type Fibonacci_GetSequenceServer interface {
	Send(*FibonacciReply) error
	grpc.ServerStream
}

type fibonacciGetSequenceServer struct {
	grpc.ServerStream
}

func (x *fibonacciGetSequenceServer) Send(m *FibonacciReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Fibonacci_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Fibonacci",
	HandlerType: (*FibonacciServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSequence",
			Handler:       _Fibonacci_GetSequence_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/fibonacci.proto",
}
